### ISSUE TITLE
Releases does not contain binaries.

### ISSUE THREAD

**Issue by TrevorBenson** [input-output-hk/bech32#38]
README.md suggests

> See [releases](https://github.com/input-output-hk/bech32/releases) for pre-compiled binary artifacts.

The page however only contains source code in the artifacts.

Please include the pre-compiled binary artifacts or update the README.md for accuracy.

**Comment by rvl** [comment]
Thanks @TrevorBenson.

The Linux static builds stopped working after GitHub Actions updated their `ubuntu-latest` image.

But don't worry, if you need pre-compiled binaries of bech32, they are bundled with [cardano-wallet](https://github.com/input-output-hk/cardano-wallet/releases) - for Linux, macOS, and Windows.

I'll update the `README.md`.
