### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rnbguy** [input-output-hk/bech32#46]
Thanks for this nifty tool.

Do you mind adding a license to this work?

While packaging it for [AUR](https://aur.archlinux.org/packages/bech32-cli-bin), I realized it does not contain any license.

**Comment by rvl** [comment]
Thanks @rnbguy. Here are the license files:
1. https://github.com/input-output-hk/bech32/blob/master/bech32/LICENSE
2. https://github.com/input-output-hk/bech32/blob/master/bech32-th/LICENSE
